apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-env
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/part-of: jenkins
    app.kubernetes.io/scope: devops-with-saeid
    app.kubernetes.io/created-by: ssbostan
data:
  REGISTRY_FIELDS_ENVIRONMENT: production
  REGISTRY_HTTP_ADDR: 0.0.0.0:443
  REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
  REGISTRY_HTTP_TLS_KEY: /certs/registry.key
