apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.name.glusterfs }}
  labels:
    endpoint: {{ .Values.name.glusterfs }}
subsets:
  - addresses:
      - ip: 192.168.143.22
        hostname: gluster-1
      - ip: 192.168.143.35
        hostname: gluster-2
      - ip: 192.168.143.44
        hostname: gluster-3
    ports:
      - port: 1
      