apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.heketi }}

spec:
  type: {{ .Values.servicetype }}
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000
    protocol: TCP
    name: node-port-heketi

  selector:
    deploy: {{ .Values.name.heketi }}