apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  # namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      deploy: {{ .Values.name }}
  template:
    metadata:
      labels:
        deploy: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
          ports:
            - containerPort: {{ .Values.container.port1 }}
              name: {{ .Values.container.port1name }}
            - containerPort: {{ .Values.container.port1 }}
              name: {{ .Values.container.port2name }}
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data

      # initContainers:
      # - name: volume-mount-hack
      #   image: busybox
      #   command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
      #   volumeMounts:
      #   - name: <your nexus pvc volume name>
      #     mountPath: /nexus-data



      # volumes:
      #   - name: nexus-data
      #     emptyDir: {}
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: {{ .Values.name }}