apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}

data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJuZXh1czozMjAwMiI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZNVEl6TkNGQUl5UnhkMlU9IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy42IChsaW51eCkiCgl9Cn0=
type: kubernetes.io/dockerconfigjson