apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}
  labels:
    pv: {{ .Values.name }}
spec:
  storageClassName: {{ .Values.name }}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: "/volumes/zoo"
