apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    service: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 2181
    protocol: TCP
  # - name: follower
  #   port: 2888
  #   protocol: TCP
  # - name: leader
  #   port: 3888
  #   protocol: TCP

  selector:
    deploy: {{ .Values.name }} 
