apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-data
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: docker
    app.kubernetes.io/part-of: jenkins
    app.kubernetes.io/scope: devops-with-saeid
    app.kubernetes.io/created-by: ssbostan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-certs
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: docker
    app.kubernetes.io/part-of: jenkins
    app.kubernetes.io/scope: devops-with-saeid
    app.kubernetes.io/created-by: ssbostan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-certs-client
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: docker
    app.kubernetes.io/part-of: jenkins
    app.kubernetes.io/scope: devops-with-saeid
    app.kubernetes.io/created-by: ssbostan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
