apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    service: {{ .Values.name }}
spec:
  ports:
  - port: 9093
    name: web
  ports:
  - port: 9092
    name: connection
  clusterIP: None
  selector:
    service: {{ .Values.name }}
