apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  labels:
    statefulset: {{ .Values.name }}
spec:
  serviceName: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      statefulset: {{ .Values.matchLabels}}
  template:
    metadata:
      labels:
        statefulset: {{ .Values.matchLabels }}  # has to match .spec.template.metadata.labels
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9092
          name: inside
        - containerPort: 9093
          name: outside
        resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

        command:
        - sh
        - -c
        - "exec kafka-server-start.sh /opt/bitnami/kafka/config/server.properties --override broker.id=${HOSTNAME##*-} \
          --override zookeeper.connect=zookeeper.default.svc.cluster.local:2181"
          # --override advertised.listeners=INSIDE://$HOSTNAME:9092,OUTSIDE://$HOSTNAME.kafka-service.default.svc.cluster.local:9093 \
          # --override listener.security.protocol.map=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        env:
          # - name: KAFKA_CFG_BROKER_ID
          #   # value: HOSTNAME_COMMAND
            # value: $HOSTNAME | rev | cut -d'-' -f1 | rev
            # value: hostname | awk -F'-' '{print $$2}'
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
          - name: KAFKA_CFG_LISTENERS
            value: INSIDE://:9092,OUTSIDE://:9093
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: INSIDE://:9092,OUTSIDE://$HOSTNAME.kafka.default.svc.cluster.local:9093
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: INSIDE
          - name: KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE
            value: "true"
          # - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            # value: zookeeper.default.svc.cluster.local:2181

        volumeMounts:
        - mountPath: /bitnami/kafka
          name: {{ .Values.name }}


  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.name }}
    spec:
      storageClassName: manual
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      selector:
        matchLabels:
          type: local