apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: jenkins
    app.kubernetes.io/scope: devops-with-saeid
    app.kubernetes.io/created-by: ssbostan
spec:
  type: LoadBalancer
  ports:
    - name: jenkins-agents
      port: 50000
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/scope: devops-with-saeid
    app.kubernetes.io/created-by: ssbostan
