apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  labels:
    service: {{ .Values.name }}
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 31000
    protocol: TCP
    name: nodeportelastic
  selector:
    deploy: {{ .Values.name }} 