kind: PersistentVolume
apiVersion: v1
metadata:
  name: test01
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/test/kafka01"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: test02
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/test/kafka02"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: test03
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/test/kafka03"
---